services:
  arduinocommunicationserver:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
          - ardudb
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      telegram.bot.token: ${TELEGRAM_BOT_TOKEN}
      telegram.bot.chatId: ${TELEGRAM_CHAT_ID}
      EMAIL_SENDER: ${EMAIL_SENDER}
      EMAIL_RECEIVER: ${EMAIL_RECEIVER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

  ardudb:
    image: mysql:8.0
    container_name: ardudb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"


volumes:
  db-data:
    driver: local